# client service
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

---
# server service
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31500
  type: NodePort

---
# ml service
apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  selector:
    app: ml
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP

---
# cpy service
apiVersion: v1
kind: Service
metadata:
  name: cpy-service
spec:
  selector:
    app: cpy
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP
